apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-dashboard-extension
  labels: 
    app: tekton-dashboard-extension-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-dashboard-extension
  template:
    metadata:
      name: tekton-dashboard-extension
      labels:
        app: tekton-dashboard-extension
    spec:
      containers:
      - name: tekton-dashboard-extension
        image: <image name>:<image tag>
        ports:
        - containerPort: 3000

